apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: serviceproject01-svpc-01
  labels:
    environment: "dev"
  name: test-topic-config-connector
  namespace: default
spec:
  schemaSettings:
    schemaRef:
      name: pubsubtopic-dep
    encoding: JSON
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSchema
metadata:
  name: pubsubtopic-dep
  namespace: default
spec:
  type: PROTOCOL_BUFFER
  definition: "syntax = \"proto3\";\nmessage Results {\nstring message_request = 1;\nstring message_response = 2;\nstring timestamp_request = 3;\nstring timestamp_response = 4;\n}"
  projectRef:
    external: serviceproject01-svpc-01